// Generated by tools/generate_ts_registry.py -- do not edit by hand.
// Sources:
//   docs/bmcu_binary_registry.json (BMB1 revision 1)
//   docs/bmcu_link_enum_registry.json (alpha.3, wire 131)

export const WIRE_ENDIANNESS = "big"
export const LINK_WIRE_PROTOCOL = 131

/** BMB1 message_types */
export const MessageType = {
  ServerChallenge: 1,
  Hello: 2,
  HelloAccepted: 3,
  BmcuFrame: 16,
  LinkState: 17,
  TransportDrop: 18,
  PicoDiagnostic: 19,
  PicoLog: 20,
  Ack: 32,
  Control: 48,
  ControlResult: 49,
  Ping: 64,
  Pong: 65,
  ProtocolError: 127,
} as const
export type MessageType = (typeof MessageType)[keyof typeof MessageType]

/** BMB1 flags */
export const Flag = {
  Replay: 1,
  Critical: 2,
  Snapshot: 4,
  WallTimeValid: 8,
  Journaled: 16,
} as const
export type Flag = (typeof Flag)[keyof typeof Flag]

/** BMB1 value_types */
export const ValueType = {
  Uint8: 1,
  Uint16: 2,
  Uint32: 3,
  Uint64: 4,
  Int8: 5,
  Int16: 6,
  Int32: 7,
  Int64: 8,
  Bool: 9,
  Utf8: 10,
  Bytes: 11,
} as const
export type ValueType = (typeof ValueType)[keyof typeof ValueType]

/** BMB1 link_states */
export const LinkState = {
  Unknown: 0,
  Resyncing: 1,
  Online: 2,
  Stale: 3,
  Offline: 4,
  Incompatible: 5,
} as const
export type LinkState = (typeof LinkState)[keyof typeof LinkState]

/** BMB1 link_reasons */
export const LinkReason = {
  Unspecified: 0,
  FrameReceived: 1,
  ResponseTimeout: 2,
  UartError: 3,
  ProtocolVersion: 4,
  ResyncRequested: 5,
  DeviceReboot: 6,
} as const
export type LinkReason = (typeof LinkReason)[keyof typeof LinkReason]

/** BMB1 log_severity */
export const LogSeverity = {
  Debug: 0,
  Info: 1,
  Notice: 2,
  Warning: 3,
  Error: 4,
  Critical: 5,
} as const
export type LogSeverity = (typeof LogSeverity)[keyof typeof LogSeverity]

/** BMB1 drop_reasons */
export const DropReason = {
  Unknown: 0,
  RamQueueFull: 1,
  JournalFull: 2,
  JournalCorrupt: 3,
  RecordTooLarge: 4,
  RetentionEviction: 5,
} as const
export type DropReason = (typeof DropReason)[keyof typeof DropReason]

/** BMB1 reject_reasons */
export const RejectReason = {
  Unknown: 0,
  Malformed: 1,
  Unsupported: 2,
  InvalidBmcuFrame: 3,
  PersistenceFailed: 4,
} as const
export type RejectReason = (typeof RejectReason)[keyof typeof RejectReason]

/** BMB1 control_commands */
export const ControlCommand = {
  SoftReset: 1,
} as const
export type ControlCommand = (typeof ControlCommand)[keyof typeof ControlCommand]

/** BMB1 control_result_codes */
export const ControlResult = {
  Ok: 0,
  Expired: 1,
  Replayed: 2,
  Unauthenticated: 3,
  UnknownCommand: 4,
  Unsafe: 5,
  InvalidArgument: 6,
  InternalError: 7,
} as const
export type ControlResult = (typeof ControlResult)[keyof typeof ControlResult]

/** BMB1 protocol_error_codes */
export const ProtocolErrorCode = {
  MalformedHeader: 1,
  PayloadTooLarge: 2,
  AuthenticationFailed: 3,
  UnexpectedMessage: 4,
  InvalidPayload: 5,
  ReplayedControl: 6,
} as const
export type ProtocolErrorCode = (typeof ProtocolErrorCode)[keyof typeof ProtocolErrorCode]

/** BMB1 diagnostic_tags */
export const Diag = {
  UptimeMs: 1,
  ResetReason: 2,
  Firmware: 3,
  HeapFree: 4,
  HeapAllocated: 5,
  HeapMinFree: 6,
  TemperatureMilliC: 7,
  GcCount: 8,
  LoopBusyUs: 9,
  LoopIdleUs: 10,
  LoopMaxDelayUs: 11,
  LoopGapAvgUs: 12,
  LoopGapP95Us: 13,
  LoopGapP99Us: 14,
  WifiState: 16,
  WifiRssiDbm: 17,
  WifiReconnectCount: 18,
  TcpState: 24,
  TcpRxBytes: 25,
  TcpTxBytes: 26,
  TcpReconnectCount: 27,
  AckAgeMs: 28,
  LastAckWatermark: 29,
  ReplayCount: 30,
  TransportEncodeAvgUs: 31,
  QueueDepth: 32,
  QueueDropCount: 33,
  OldestUnacknowledgedSequence: 34,
  StatusReplacementCount: 35,
  TransportSendAvgUs: 36,
  TransportSendMaxUs: 37,
  JournalUsedBytes: 40,
  JournalFreeBytes: 41,
  JournalFailureCount: 42,
  JournalOldestUs: 43,
  JournalNewestUs: 44,
  ExceptionCount: 48,
  GcTimeUs: 49,
  GcMaxTimeUs: 50,
  Uart0Backlog: 64,
  Uart0MaxBacklog: 65,
  Uart0RxBytes: 66,
  Uart0CrcErrors: 67,
  Uart0FrameErrors: 68,
  Uart0SequenceGaps: 69,
  Uart0ResyncCount: 70,
  Uart0MaxServiceDelayUs: 71,
  Uart1Backlog: 72,
  Uart1MaxBacklog: 73,
  Uart1RxBytes: 74,
  Uart1CrcErrors: 75,
  Uart1FrameErrors: 76,
  Uart1SequenceGaps: 77,
  Uart1ResyncCount: 78,
  Uart1MaxServiceDelayUs: 79,
  Uart0DrainBytes: 80,
  Uart0OverflowCount: 81,
  Uart1DrainBytes: 82,
  Uart1OverflowCount: 83,
  JournalStageFailureCount: 84,
  RejectDurableFullCount: 85,
  RejectLargeFullCount: 86,
  RejectOversizeCount: 87,
  RejectRingErrorCount: 88,
  DurableDepthMax: 89,
} as const
export type Diag = (typeof Diag)[keyof typeof Diag]

/** BMB1 limits */
export const Limit = {
  HeaderSize: 32,
  MaxPayloadSize: 4096,
  MaxDeviceIdBytes: 63,
  MaxFirmwareBytes: 63,
  MaxLinkCount: 2,
  MaxLinkIdBytes: 31,
  MaxReplayBootRanges: 8,
  MaxControlArgumentBytes: 128,
  MaxErrorDetailBytes: 160,
  MaxControlResultDetailBytes: 160,
  MaxLogComponentBytes: 40,
  MaxLogMessageBytes: 320,
  MaxLogDetailBytes: 512,
  MaxLocalLogRecords: 64,
  MaxLocalLogResponseBytes: 32768,
} as const
export type Limit = (typeof Limit)[keyof typeof Limit]

/** BMB1 scope */
export const Scope = {
  Global: 255,
} as const
export type Scope = (typeof Scope)[keyof typeof Scope]

/** BMCU Link ack_result */
export const BmcuAckResult = {
  Ok: 0,
  BadValue: 1,
  Unsupported: 2,
  Busy: 3,
  BadState: 4,
  Denied: 5,
  Expired: 6,
  Duplicate: 7,
  Internal: 8,
} as const
export type BmcuAckResult = (typeof BmcuAckResult)[keyof typeof BmcuAckResult]

/** BMCU Link capability */
export const BmcuCapability = {
  StatusEvents: 1,
  LedOverride: 2,
  PingPong: 4,
  RawHwTick: 8,
  PrinterTrace: 16,
  SensorRecord: 32,
  FullStatus: 64,
  SoftReset: 128,
} as const
export type BmcuCapability = (typeof BmcuCapability)[keyof typeof BmcuCapability]

/** BMCU Link command_owner */
export const BmcuCommandOwner = {
  None: 0,
  Printer: 1,
  User: 2,
  BmcuLocal: 3,
  Safety: 4,
  System: 5,
} as const
export type BmcuCommandOwner = (typeof BmcuCommandOwner)[keyof typeof BmcuCommandOwner]

/** BMCU Link diag_counter */
export const BmcuDiagCounter = {
  AmsServiceGapMs: 1,
  AmsWouldReoffer: 2,
  MergerTailHeld: 3,
  MergerTailPreempted: 4,
} as const
export type BmcuDiagCounter = (typeof BmcuDiagCounter)[keyof typeof BmcuDiagCounter]

/** BMCU Link dm_teardown_cause */
export const BmcuDmTeardownCause = {
  KsDeviated: 1,
  KsEmpty: 2,
  Timeout: 3,
  GlobalClear: 4,
  BufferAbort: 5,
} as const
export type BmcuDmTeardownCause = (typeof BmcuDmTeardownCause)[keyof typeof BmcuDmTeardownCause]

/** BMCU Link full_status_record_type */
export const BmcuFullStatusRecordType = {
  Global: 1,
  Channel: 2,
  PrinterBus: 3,
  Counters: 4,
  PrinterAuth: 5,
  PrinterRxCore: 6,
  PrinterRxLoss: 7,
  PrinterRxDma: 8,
  PrinterTxCore: 9,
  PrinterTxFault: 10,
  AmsService: 11,
  AmsRegistration: 12,
  Probe: 13,
  DmKey: 14,
} as const
export type BmcuFullStatusRecordType = (typeof BmcuFullStatusRecordType)[keyof typeof BmcuFullStatusRecordType]

/** BMCU Link full_status_section */
export const BmcuFullStatusSection = {
  Global: 1,
  Channels: 2,
  PrinterBus: 4,
  Counters: 8,
  All: 15,
} as const
export type BmcuFullStatusSection = (typeof BmcuFullStatusSection)[keyof typeof BmcuFullStatusSection]

/** BMCU Link kind */
export const BmcuKind = {
  Hello: 1,
  Status: 2,
  Event: 3,
  PrinterTransaction: 4,
  SensorRecord: 5,
  GetStatus: 16,
  SetLedMode: 17,
  Ping: 18,
  GetFullStatus: 23,
  RequestSoftReset: 24,
  Pong: 114,
  FullStatusRecord: 115,
  Ack: 127,
} as const
export type BmcuKind = (typeof BmcuKind)[keyof typeof BmcuKind]

/** BMCU Link outcome */
export const BmcuOutcome = {
  Accepted: 0,
  Applied: 1,
  Replied: 2,
  Ignored: 3,
  Rejected: 4,
  Failed: 5,
} as const
export type BmcuOutcome = (typeof BmcuOutcome)[keyof typeof BmcuOutcome]

/** BMCU Link reason */
export const BmcuReason = {
  Ok: 0,
  TargetMismatch: 1,
  SlotRange: 2,
  AmsOffline: 3,
  InvalidLength: 4,
  InvalidCrc: 5,
  Unsupported: 6,
  NoHandler: 7,
  TxBusy: 8,
  BadState: 9,
  SafetyInhibit: 10,
  Internal: 11,
  OwnerConflict: 12,
  LeaseExpired: 13,
  NoResponse: 14,
  NoResponseExpected: 15,
} as const
export type BmcuReason = (typeof BmcuReason)[keyof typeof BmcuReason]

/** BMCU Link record_type */
export const BmcuRecordType = {
  Boot: 1,
  PrinterLink: 2,
  PrinterTransaction: 3,
  StateChange: 4,
  Sensor: 5,
  CommandResult: 6,
  SafetyDecision: 7,
  DiagnosticCounter: 8,
  PrinterLongTransaction: 9,
  ResetState: 10,
  DmTeardown: 11,
} as const
export type BmcuRecordType = (typeof BmcuRecordType)[keyof typeof BmcuRecordType]

/** BMCU Link reset_cancel_reason */
export const BmcuResetCancelReason = {
  None: 0,
  SafetyChanged: 1,
  Expired: 2,
  LinkTxFault: 3,
} as const
export type BmcuResetCancelReason = (typeof BmcuResetCancelReason)[keyof typeof BmcuResetCancelReason]

/** BMCU Link reset_state */
export const BmcuResetState = {
  Scheduled: 1,
  Cancelled: 2,
} as const
export type BmcuResetState = (typeof BmcuResetState)[keyof typeof BmcuResetState]

/** BMCU Link sensor_validity */
export const BmcuSensorValidity = {
  Unknown: 0,
  Valid: 1,
  Stale: 2,
  Offline: 3,
  Fault: 4,
} as const
export type BmcuSensorValidity = (typeof BmcuSensorValidity)[keyof typeof BmcuSensorValidity]

/** BMCU Link severity */
export const BmcuSeverity = {
  Debug: 0,
  Info: 1,
  Notice: 2,
  Warning: 3,
  Error: 4,
  Critical: 5,
} as const
export type BmcuSeverity = (typeof BmcuSeverity)[keyof typeof BmcuSeverity]

/** BMCU Link source */
export const BmcuSource = {
  System: 0,
  PrinterBus: 1,
  Motion: 2,
  Sensor: 3,
  Management: 4,
  Safety: 5,
} as const
export type BmcuSource = (typeof BmcuSource)[keyof typeof BmcuSource]

/** BMCU Link state_field */
export const BmcuStateField = {
  Slot: 1,
  InsertedMask: 2,
  OnlineMask: 3,
  Motion: 4,
  Pressure: 5,
  LedMode: 6,
  ControlError: 7,
  MotionFault: 8,
} as const
export type BmcuStateField = (typeof BmcuStateField)[keyof typeof BmcuStateField]

