"""BMB1 wire constants. Keep in sync with docs/bmcu_binary_registry.json."""

MAGIC = b"BMB1"
VERSION = 1
HEADER_SIZE = 32
GLOBAL_SCOPE = 0xFF
MAX_PAYLOAD_SIZE = 4096
MAX_MESSAGE_SIZE = HEADER_SIZE + MAX_PAYLOAD_SIZE

SERVER_CHALLENGE = 0x01
HELLO = 0x02
HELLO_ACCEPTED = 0x03
BMCU_FRAME = 0x10
LINK_STATE = 0x11
TRANSPORT_DROP = 0x12
PICO_DIAGNOSTIC = 0x13
PICO_LOG = 0x14
ACK = 0x20
CONTROL = 0x30
CONTROL_RESULT = 0x31
PING = 0x40
PONG = 0x41
PROTOCOL_ERROR = 0x7F

FLAG_REPLAY = 1 << 0
FLAG_CRITICAL = 1 << 1
FLAG_SNAPSHOT = 1 << 2
FLAG_WALL_TIME_VALID = 1 << 3
FLAG_JOURNALED = 1 << 4
KNOWN_FLAGS = 0x001F

VALUE_UINT8 = 1
VALUE_UINT16 = 2
VALUE_UINT32 = 3
VALUE_UINT64 = 4
VALUE_INT8 = 5
VALUE_INT16 = 6
VALUE_INT32 = 7
VALUE_INT64 = 8
VALUE_BOOL = 9
VALUE_UTF8 = 10
VALUE_BYTES = 11

LINK_UNKNOWN = 0
LINK_RESYNCING = 1
LINK_ONLINE = 2
LINK_STALE = 3
LINK_OFFLINE = 4
LINK_INCOMPATIBLE = 5

LINK_REASON_UNSPECIFIED = 0
LINK_REASON_FRAME_RECEIVED = 1
LINK_REASON_RESPONSE_TIMEOUT = 2
LINK_REASON_UART_ERROR = 3
LINK_REASON_PROTOCOL_VERSION = 4
LINK_REASON_RESYNC_REQUESTED = 5
LINK_REASON_DEVICE_REBOOT = 6

LOG_DEBUG = 0
LOG_INFO = 1
LOG_NOTICE = 2
LOG_WARNING = 3
LOG_ERROR = 4
LOG_CRITICAL = 5

DROP_UNKNOWN = 0
DROP_RAM_QUEUE_FULL = 1
DROP_JOURNAL_FULL = 2
DROP_JOURNAL_CORRUPT = 3
DROP_RECORD_TOO_LARGE = 4
DROP_RETENTION_EVICTION = 5

REJECT_UNKNOWN = 0
REJECT_MALFORMED = 1
REJECT_UNSUPPORTED = 2
REJECT_INVALID_BMCU_FRAME = 3
REJECT_PERSISTENCE_FAILED = 4

CONTROL_SOFT_RESET = 1

RESULT_OK = 0
RESULT_EXPIRED = 1
RESULT_REPLAYED = 2
RESULT_UNAUTHENTICATED = 3
RESULT_UNKNOWN_COMMAND = 4
RESULT_UNSAFE = 5
RESULT_INVALID_ARGUMENT = 6
RESULT_INTERNAL_ERROR = 7

PROTOCOL_ERROR_MALFORMED_HEADER = 1
PROTOCOL_ERROR_PAYLOAD_TOO_LARGE = 2
PROTOCOL_ERROR_AUTHENTICATION_FAILED = 3
PROTOCOL_ERROR_UNEXPECTED_MESSAGE = 4
PROTOCOL_ERROR_INVALID_PAYLOAD = 5
PROTOCOL_ERROR_REPLAYED_CONTROL = 6

DIAG_UPTIME_MS = 1
DIAG_RESET_REASON = 2
DIAG_FIRMWARE = 3
DIAG_HEAP_FREE = 4
DIAG_HEAP_ALLOCATED = 5
DIAG_HEAP_MIN_FREE = 6
DIAG_TEMPERATURE_MILLI_C = 7
DIAG_GC_COUNT = 8
DIAG_LOOP_BUSY_US = 9
DIAG_LOOP_IDLE_US = 10
DIAG_LOOP_MAX_DELAY_US = 11
DIAG_WIFI_STATE = 16
DIAG_WIFI_RSSI_DBM = 17
DIAG_WIFI_RECONNECT_COUNT = 18
DIAG_TCP_STATE = 24
DIAG_TCP_RX_BYTES = 25
DIAG_TCP_TX_BYTES = 26
DIAG_TCP_RECONNECT_COUNT = 27
DIAG_ACK_AGE_MS = 28
DIAG_LAST_ACK_WATERMARK = 29
DIAG_REPLAY_COUNT = 30
DIAG_QUEUE_DEPTH = 32
DIAG_QUEUE_DROP_COUNT = 33
DIAG_OLDEST_UNACKNOWLEDGED_SEQUENCE = 34
DIAG_STATUS_REPLACEMENT_COUNT = 35
DIAG_JOURNAL_USED_BYTES = 40
DIAG_JOURNAL_FREE_BYTES = 41
DIAG_JOURNAL_FAILURE_COUNT = 42
DIAG_JOURNAL_OLDEST_US = 43
DIAG_JOURNAL_NEWEST_US = 44
DIAG_EXCEPTION_COUNT = 48
DIAG_UART0_BACKLOG = 64
DIAG_UART0_MAX_BACKLOG = 65
DIAG_UART0_RX_BYTES = 66
DIAG_UART0_CRC_ERRORS = 67
DIAG_UART0_FRAME_ERRORS = 68
DIAG_UART0_SEQUENCE_GAPS = 69
DIAG_UART0_RESYNC_COUNT = 70
DIAG_UART0_MAX_SERVICE_DELAY_US = 71
DIAG_UART1_BACKLOG = 72
DIAG_UART1_MAX_BACKLOG = 73
DIAG_UART1_RX_BYTES = 74
DIAG_UART1_CRC_ERRORS = 75
DIAG_UART1_FRAME_ERRORS = 76
DIAG_UART1_SEQUENCE_GAPS = 77
DIAG_UART1_RESYNC_COUNT = 78
DIAG_UART1_MAX_SERVICE_DELAY_US = 79

MAX_DEVICE_ID_BYTES = 63
MAX_FIRMWARE_BYTES = 63
MAX_LINK_COUNT = 2
MAX_LINK_ID_BYTES = 31
MAX_REPLAY_BOOT_RANGES = 8
MAX_CONTROL_ARGUMENT_BYTES = 128
MAX_ERROR_DETAIL_BYTES = 160
MAX_CONTROL_RESULT_DETAIL_BYTES = 160
MAX_LOG_COMPONENT_BYTES = 40
MAX_LOG_MESSAGE_BYTES = 320
MAX_LOG_DETAIL_BYTES = 512
