"""Generate TypeScript wire constants for the web UI from the JSON registries.

The browser UI used to hand-copy every tag number and struct offset out of
``pico/bmcu_binary_constants.py``. Renumbering a TLV tag then broke the UI
silently. Everything a machine-readable registry already knows is emitted here
instead, so a renumbered enum becomes a TypeScript compile error.

Offsets that no registry describes live in ``web/src/api/layout.ts`` and are
pinned by fixture round-trip tests rather than by codegen.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINARY_REGISTRY = ROOT / "docs" / "bmcu_binary_registry.json"
LINK_REGISTRY = ROOT / "docs" / "bmcu_link_enum_registry.json"
OUTPUT = ROOT / "web" / "src" / "api" / "generated.ts"

# Registry group -> exported TypeScript name. Groups absent from this table are
# skipped deliberately: an unmapped group means the registry grew a section the
# UI has not been taught to read, which should be an explicit decision.
BINARY_GROUPS = {
    "message_types": "MessageType",
    "flags": "Flag",
    "value_types": "ValueType",
    "link_states": "LinkState",
    "link_reasons": "LinkReason",
    "log_severity": "LogSeverity",
    "drop_reasons": "DropReason",
    "reject_reasons": "RejectReason",
    "control_commands": "ControlCommand",
    "control_result_codes": "ControlResult",
    "protocol_error_codes": "ProtocolErrorCode",
    "diagnostic_tags": "Diag",
    "limits": "Limit",
    "scope": "Scope",
}

# The link registry describes the BMCU-side wire protocol, the binary registry
# the Pico<->Bambuddy transport. Both define a "reason" enum, so the BMCU side
# is prefixed rather than left to collide.
LINK_PREFIX = "Bmcu"


def pascal(name):
    return "".join(part.capitalize() for part in name.split("_") if part)


def emit_enum(export_name, members, source):
    lines = ["/** %s */" % source,
             "export const %s = {" % export_name]
    for key, value in members:
        lines.append("  %s: %d," % (pascal(key), value))
    lines.append("} as const")
    lines.append("export type %s = (typeof %s)[keyof typeof %s]"
                 % (export_name, export_name, export_name))
    lines.append("")
    return lines


def numeric_members(group):
    # Registries mix documentation strings into value maps (scope carries a
    # prose "ack_watermark" note); only integers are wire constants.
    return [(key, value) for key, value in group.items()
            if isinstance(value, int) and not isinstance(value, bool)]


def inverted_members(group):
    """Link registry groups are stored value -> name, the other way round."""
    members = []
    for value, name in group.items():
        try:
            members.append((name, int(value)))
        except (TypeError, ValueError):
            continue
    members.sort(key=lambda item: item[1])
    return members


def render(binary_registry, link_registry):
    lines = [
        "// Generated by tools/generate_ts_registry.py -- do not edit by hand.",
        "// Sources:",
        "//   docs/bmcu_binary_registry.json (%s revision %s)"
        % (binary_registry.get("registry"), binary_registry.get("revision")),
        "//   docs/bmcu_link_enum_registry.json (%s, wire %s)"
        % (link_registry.get("registry_version"),
           link_registry.get("wire_protocol")),
        "",
        "export const WIRE_ENDIANNESS = %s"
        % json.dumps(binary_registry.get("wire_endianness", "big")),
        "export const LINK_WIRE_PROTOCOL = %d"
        % link_registry.get("wire_protocol", 0),
        "",
    ]
    exported = {}

    def add(export_name, members, source):
        if not members:
            raise SystemExit("registry group %r produced no members" % source)
        if export_name in exported:
            raise SystemExit(
                "export name %r is claimed by both %r and %r"
                % (export_name, exported[export_name], source))
        exported[export_name] = source
        lines.extend(emit_enum(export_name, members, source))

    for group_name, export_name in BINARY_GROUPS.items():
        group = binary_registry.get(group_name)
        if not group:
            raise SystemExit(
                "docs/bmcu_binary_registry.json is missing group %r"
                % group_name)
        add(export_name, numeric_members(group), "BMB1 %s" % group_name)
    for group_name, group in sorted(link_registry.get("enums", {}).items()):
        add(LINK_PREFIX + pascal(group_name), inverted_members(group),
            "BMCU Link %s" % group_name)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail instead of writing when the output drifts")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    arguments = parser.parse_args()

    binary_registry = json.loads(BINARY_REGISTRY.read_text(encoding="utf-8"))
    link_registry = json.loads(LINK_REGISTRY.read_text(encoding="utf-8"))
    rendered = render(binary_registry, link_registry) + "\n"

    if arguments.check:
        # newline="" keeps read and write symmetric: .gitattributes normalises
        # this file to LF, so a Windows checkout that translated on write would
        # report drift against an identical file.
        # Path.read_text gained newline= only in 3.13; open() has always had it.
        current = ""
        if arguments.output.exists():
            with arguments.output.open(encoding="utf-8", newline="") as handle:
                current = handle.read()
        if current != rendered:
            raise SystemExit(
                "%s is stale; run tools/generate_ts_registry.py"
                % arguments.output.relative_to(ROOT))
        return
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
