import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Plugin } from 'vite'
import { viteSingleFile } from 'vite-plugin-singlefile'
// vitest/config re-exports Vite's defineConfig with the `test` block typed.
import { defineConfig } from 'vitest/config'

const here = dirname(fileURLToPath(import.meta.url))
const mockDir = resolve(here, 'src/mock/fixtures')

const BINARY_TYPE = 'application/vnd.bmcu-monitor.v1'

const ENVELOPE_SIZE = 32
const PAYLOAD_LENGTH_OFFSET = 8
const LOG_SEQUENCE_OFFSET = 0

/**
 * The device's /api/logs.bin is a delta endpoint: it returns only records past
 * `after`. A mock that ignores the cursor replays the same lines every poll,
 * which looks like a UI bug that does not exist on hardware.
 */
function logsAfter(buffer: Buffer, after: bigint): Buffer {
  const kept: Buffer[] = []
  let offset = 0
  while (offset + ENVELOPE_SIZE <= buffer.length) {
    const length = buffer.readUInt32BE(offset + PAYLOAD_LENGTH_OFFSET)
    const end = offset + ENVELOPE_SIZE + length
    if (end > buffer.length) break
    const sequence = buffer.readBigUInt64BE(
      offset + ENVELOPE_SIZE + LOG_SEQUENCE_OFFSET,
    )
    if (sequence > after) kept.push(buffer.subarray(offset, end))
    offset = end
  }
  return Buffer.concat(kept)
}

/**
 * Serves the same endpoints the Pico serves, from fixtures generated by
 * tools/generate_web_mock_fixtures.py with the real Pico encoders. This is
 * what makes the UI developable without a device on the bench.
 */
function mockPico(): Plugin {
  const binary = (name: string) => readFileSync(resolve(mockDir, name))
  const text = (name: string) => readFileSync(resolve(mockDir, name), 'utf8')
  return {
    name: 'mock-pico',
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const [url = '', query = ''] = (request.url ?? '').split('?')
        if (!url.startsWith('/api/')) return next()
        try {
          if (url === '/api/current.bin') return send(binary('current.bin'))
          if (url === '/api/diagnostics.bin') return send(binary('diagnostics.bin'))
          if (url === '/api/snapshot.bin') return send(binary('snapshot.bin'))
          if (url === '/api/logs.bin') {
            const after = new URLSearchParams(query).get('after') ?? '0'
            return send(logsAfter(binary('logs.bin'), BigInt(after)))
          }
          if (url === '/api/transport/status') return sendText(text('transport_status.txt'))
          if (url === '/api/device-key/status') return sendText(text('device_key_status.txt'))
          if (request.method === 'POST') return sendText('ok\n')
        } catch (error) {
          response.statusCode = 500
          response.end(String(error))
          return
        }
        response.statusCode = 404
        response.end('Not found\n')
        return

        function send(body: Buffer) {
          response.setHeader('Content-Type', BINARY_TYPE)
          response.end(body)
        }
        function sendText(body: string) {
          response.setHeader('Content-Type', 'text/plain; charset=utf-8')
          response.end(body)
        }
      })
    },
  }
}

export default defineConfig({
  // JSX runtime and importSource come from tsconfig.json; Vite's Oxc transform
  // reads them, so there is one place that says "this is Preact JSX".
  plugins: [mockPico(), viteSingleFile()],
  build: {
    // The page is streamed off littlefs on a Pico 2 W; every kilobyte is flash
    // and transfer time over WebREPL.
    target: 'es2022',
    cssCodeSplit: false,
    assetsInlineLimit: 100_000_000,
    chunkSizeWarningLimit: 256,
    reportCompressedSize: true,
  },
  test: {
    environment: 'node',
    include: ['test/**/*.test.ts', 'test/**/*.test.tsx'],
  },
})
